name: Builds Project Tests

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      debug:
        type: boolean
        description: 'debug'
        required: true
        default: false
env:
  project_name: eba-dflt
  location: eastus
  service_principle : $project_name-sp
  keyvault : kv-$project_name-$location
  ACTIONS_STEP_DEBUG : ${{ inputs.debug }} 
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID_NP }}

jobs:

  lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10


      - name: Terraform Init
        id: init
        env:
          TF_RESOURCE_GROUP: ${{ secrets.TF_RESOURCE_GROUP }}
          TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
          TF_CONTAINER_NAME: ${{ secrets.TF_CONTAINER_NAME }}
        run: |
          cd IaC/terraform/dev
          echo Current directory: 
          ls
          terraform init -backend-config="storage_account_name=stebadevops001" -backend-config="container_name=tf-container" -backend-config="resource_group_name=devops-tools"
  
  Plan:
      runs-on: ubuntu-latest
      env:
          TF_VAR_location: east us
          TF_VAR_storage_account_name: ebadflt001
      strategy:
        fail-fast: false
        matrix: 
          path:
            - dev
            # - qa
            # - uat
            # - prod

      steps:
      - uses: actions/checkout@v2 
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: Terraform Init
        id: init
        env:
          RESOURCE_GROUP: ${{ secrets.TF_RESOURCE_GROUP }}
          STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
          CONTAINER_NAME: ${{ secrets.TF_CONTAINER_NAME }}
        run: |
          cd IaC/terraform/dev
          echo Current directory: 
          ls
          terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"

      - name: Terraform Plan 
        id: plan
        continue-on-error: true
        run: |
          cd IaC/terraform/${{ matrix.path }}
          terraform plan -input=false -no-color -out=tfplan \
          && terraform show -no-color tfplan          

      - name: Reformat Plan
        run: |
          echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' \
          | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > plan.txt          

      - name: Put Plan in Env Var
        run: |
          PLAN=$(cat plan.txt)
          echo "PLAN<<EOF" >> $GITHUB_ENV
          echo "$PLAN" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV          

      - name: Post Plan to GitHub PR
        uses: mshick/add-pr-comment@v1
        with:
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ## ${{ matrix.path }} plan
            ```diff
            ${{ env.PLAN }}
            ```            